format = """\
[](bg:#f7DF9AA fg:#a6da95)\
[ ](bg:#a6da95 fg:black bold)\
[](fg:#a6da95 bg:#24273a)\
$username$hostname\
[](fg:#24273a bg:#89b4fa)\
$directory\
[](fg:#89b4fa bg:yellow)\
$git_branch\
$git_status\
$git_metrics\
[](fg:yellow)\
$character\
"""

#permmeso solo in zsh
right_format = """\
$all\
"""

palette = "catppuccin_mocha"

[line_break]
disabled = true # oppure true per singola riga

[directory]
format = "[  $path ]($style)"
style = "fg:#1E1E2E bg:#89b4fa"
truncate_to_repo = false
truncation_length = 5 #number of dir before truncate
truncation_symbol = '…/'#The symbol to prefix to truncated paths

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#1E1E2E bg:yellow"

[git_status]
format = '[$all_status]($style)'
style = "fg:#1E1E2E bg:yellow"
#conflicted = " "
#ahead = " "
#behind = " "
#diverged = "󰆗 "
#up_to_date = " "
#untracked = " "
#stashed = " "
#modified = " "
#staged = " "
#renamed = " "
#deleted = " "

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1E1E2E bg:yellow"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"
disabled = true

[character]
#success_symbol = '[ ➜](bold green) '
error_symbol = '[ ✗](#E84D44) '

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[hostname]
ssh_only = false
style = "(bg:#surface0 fg:text)"
format = '[$ssh_symbol](bold sapphire)[[@$hostname](bg:#24273a fg:text)]($style)'
#format = '[$ssh_symbol](bold blue)@[$hostname](bold sapphire):'
disabled = false

[username]
#style_user = 'green bold'
style_user = 'bold blue'
style_root = 'black bold'
format = '[[$user](bg:#24273a fg:text)]($style)'
disabled = false
show_always = true

[golang]
format = '[ $version](bold cyan) '



[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
black = "#11111b"
#MY additions
purple = "#26056f"
violet = "#2605ac"
deeppurple = "#260593"
lilac = "#c6a0f6"
brightYellow = "#FCF392"
macchiatoYellow = "#eed49f"
macchiatoGreen = "#a6da95"
