add_newline = false
# A minimal left prompt
format = """$username$hostname$directory$branch$all$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
#right_format = """$all""" #zsh only

[line_break]
disabled = true

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold sapphire)@[$hostname](bold blue):'
#format = '[$ssh_symbol](bold blue)@[$hostname](bold sapphire):'
disabled = false

[username]
#style_user = 'green bold'
style_user = 'bold blue'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[directory]
style = 'lavender bold'
truncate_to_repo = false
truncation_length = 5 #number of dir before truncate
truncation_symbol = '…/'#The symbol to prefix to truncated paths

[git_branch]
#symbol = '🌱 '
style = 'pink bold'

[cmd_duration]
disabled = true
#min_time = 2_000
#format = "took [$duration]($style) "
#style = "yellow"

[golang]
format = '[ $version](bold cyan) '

[git_status] #copied
format = '([$all_status$ahead_behind]($style) )'
style = "yellow" #"green"
conflicted = " "
ahead = " "
behind = " "
diverged = "󰆗 "
up_to_date = " "
untracked = " "
stashed = " "
modified = " "
staged = " "
renamed = " "
deleted = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
#MY additions
purple = "#26056f"
violet = "#2605ac"
deeppurple = "#260593"
