;per avere uno stile incrociato  si può usare questo altro glifo: 
[module/arrow0]
type=custom/text
;content = " "
content = " "
content-foreground = ${colors.snow-white2}
content-background = ${colors.snow-background}
content-font = 4
content-padding = 0

[module/arrow1]
type=custom/text
content = ""
;content-foreground = #aa08263a
content-foreground = ${colors.snow-foreground}
content-background = ${colors.snow-white2}
content-font = 4 
content-padding = 0

[module/arrow2]
type=custom/text
content = ""
content-foreground = ${colors.snow-white3}
content-background = ${colors.snow-foreground}
content-font = 4
content-padding = 0

[module/arrow3]
type=custom/text
content = ""
content-foreground = ${colors.snow-offwhite}
content-background = ${colors.snow-white3}
content-font = 4
content-padding = 0


[module/arrow4]
type=custom/text
content = ""
content-foreground = ${colors.snow-white2}
content-background = ${colors.snow-offwhite}
content-font = 4
content-padding = 0


[module/arrow5]
type=custom/text
content = ""
;content-foreground= ${colors.snow-dark}
content-foreground= #1e1e2e
content-background= ${colors.snow-white2}
content-font = 4
content-padding = 0
;

; from catppuccin
; base = #1e1e2e
; mantle = #181825
; crust = #11111b

