[bar/secondary]
width = 99.85%
height = 28pt
radius = 9

bottom = true
monitor = HDMI-2
;Require the monitor to be in connected state
monitor-strict = true
; dpi = 96
;
; Locale used to localize various module data (e.g. date)
; Expects a valid libc locale, for example: sv_SE.UTF-8
;locale = it_IT.UTF-8

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
#border-size = 4pt
border-color = #00000000
; border-bottom-size = 0
 
padding-left = 0
padding-right = 2 


module-margin = 4pt

;separator = "" 
separator = "" 
separator-foreground = ${colors.disabled}

; Fonts are defined using <font-name>;<vertical-offset>
; Font names are specified using a fontconfig pattern.
#font-0 = monospace;2
font-0 = "JetBrains Mono Nerd Font:10;2"
font-1 = "lemon:14;2"

modules-left = xworkspaces2 
 modules-center = date2
modules-right = calendar 

cursor-click = pointer
cursor-scroll = ns-resize

;fra le altre cose rende possibile use msg-quit per killare la barra
enable-ipc = true

tray-position = none

; wm-restack = generic
; wm-restack = bspwm
  wm-restack = i3

; override-redirect = true

[module/xworkspaces2]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/date2]
type = internal/date
interval = 1

date =  %H:%M
date-alt = %H:%M 󰃭 %A %d %B %Y
;date-alt = %H:%M 󰃭 %A %d-%m-%y

;format-prefix = "  "
;format-prefix-foreground = ${colors.pink}
label = %date%
label-foreground = ${colors.text}
label-underline= ${colors.lavender}
format-prefix-underline= ${colors.blue}
;label-underline= ${colors.sapphire} , anche lavender è interessante
;format-prefix-underline= ${colors.sapphire} lavender maybe
;format-background = #24283b

[module/calendar]
type = internal/date
interval = 1

date = %A %d %B %Y
date-alt = %A %d-%m-%y

format-prefix = "󰃭 "
format-prefix-foreground = ${colors.pink}
; altra scelta solida di colore può essre green o sapphire
label = %date%
label-foreground = ${colors.text}

[settings2]
screenchange-reload = true
pseudo-transparency = true


